export const tutorialConstants = {
  GETALL_TUTORIALS_REQUEST: "GETALL_TUTORIALS_REQUEST",
  GETALL_TUTORIALS_SUCCESS: "GETALL_TUTORIALS_SUCCESS",
  GETALL_TUTORIALS_FAILURE: "GETALL_TUTORIALS_FAILURE",

  SELECT_TUTORIAL: "SELECT_TUTORIAL",
};
