export const tutorialConstants = {
  GETALL_TUTORIALS_REQUEST: "GETALL_TUTORIALS_REQUEST",
  GETALL_TUTORIALS_SUCCESS: "GETALL_TUTORIALS_SUCCESS",
  GETALL_TUTORIALS_FAILURE: "GETALL_TUTORIALS_FAILURE",
  ADD_TUTORIAL_REQUEST: "ADD_TUTORIAL_REQUEST",
  SELECT_TUTORIAL: "SELECT_TUTORIAL",
};
